excluded:
  - Pods
  - Logs/DerivedData

disabled_rules:
  - blanket_disable_command

opt_in_rules:
  - force_unwrapping
  - empty_count
  - fatal_error_message

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length: 3
  excluded:
    - i
    - x
    - y
    - z
    - dx
    - dy
    - id
    - to
    - c1
    - c2
    - c