//
// BlockContract.swift
// InkOS
//
// Core Block primitive types for the Alan educational content system.
// Blocks are the fundamental unit of interactive content - composable,
// parameterizable, and renderable elements that form lessons and interactions.
//

import Foundation

// MARK: - BlockID

// Type-safe identifier for blocks.
// Uses String internally for JSON compatibility and easy debugging.
struct BlockID: Hashable, Sendable, Codable, Equatable, CustomStringConvertible {
  let rawValue: String

  init() {
    self.rawValue = UUID().uuidString
  }

  init(_ rawValue: String) {
    self.rawValue = rawValue
  }

  var description: String { rawValue }

  init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    self.rawValue = try container.decode(String.self)
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(rawValue)
  }
}

// MARK: - BlockSchemaVersion

// Schema version for Block format migration.
enum BlockSchemaVersion {
  static let current = 1
  static let supported: Set<Int> = [1]
}

// MARK: - BlockMetadata

// Metadata about a block's creation and modification.
struct BlockMetadata: Sendable, Codable, Equatable {
  // Timestamp when block was created.
  let createdAt: Date

  // Timestamp when block was last modified.
  var modifiedAt: Date

  // Optional creator identifier (AI model, user, system).
  let createdBy: String?

  // Schema version for migration.
  let schemaVersion: Int

  private enum CodingKeys: String, CodingKey {
    case createdAt
    case modifiedAt
    case createdBy
    case schemaVersion
  }

  init(
    createdAt: Date = Date(),
    modifiedAt: Date = Date(),
    createdBy: String? = nil,
    schemaVersion: Int = BlockSchemaVersion.current
  ) {
    self.createdAt = createdAt
    self.modifiedAt = modifiedAt
    self.createdBy = createdBy
    self.schemaVersion = schemaVersion
  }
}

// MARK: - BlockSource

// How a block was created.
enum BlockSource: String, Sendable, Codable, Equatable {
  // Generated by AI or system.
  case generated

  // Created from user input.
  case userInput

  // Pinned from a conversation branch.
  case pinned

  // Imported from external source.
  case imported

  // Template/preset block.
  case template
}

// MARK: - Block

// The fundamental unit of interactive content in InkOS.
// Blocks are composable, parameterizable, and renderable.
struct Block: Identifiable, Sendable, Equatable {
  // Unique identifier for this block.
  let id: BlockID

  // The kind/type of this block determining rendering and behavior.
  let kind: BlockKind

  // Type-safe properties specific to this block kind.
  let properties: BlockProperties

  // Optional user-configurable parameters (sliders, toggles, etc.).
  let parameters: [Parameter]?

  // Child blocks for compositional structures.
  let children: [Block]?

  // Current state of this block.
  var state: BlockState

  // Metadata about creation and modification.
  let metadata: BlockMetadata

  // Actions this block can trigger.
  let actions: [BlockAction]?

  // Layer depth for conversation threading (0 = main, 1+ = nested).
  let layer: Int

  // How this block was created.
  let source: BlockSource

  // Initializer with defaults for optional fields.
  init(
    id: BlockID = BlockID(),
    kind: BlockKind,
    properties: BlockProperties,
    parameters: [Parameter]? = nil,
    children: [Block]? = nil,
    state: BlockState = .idle,
    metadata: BlockMetadata = BlockMetadata(),
    actions: [BlockAction]? = nil,
    layer: Int = 0,
    source: BlockSource = .generated
  ) {
    self.id = id
    self.kind = kind
    self.properties = properties
    self.parameters = parameters
    self.children = children
    self.state = state
    self.metadata = metadata
    self.actions = actions
    self.layer = layer
    self.source = source
  }
}
