#!/bin/bash
set -euo pipefail

# Navigate to the project root
cd "$(dirname "$0")/.."

mkdir -p ./Logs
rm -f ./Logs/build_logs.txt

echo "Building PaperClip..."

DESTINATION="generic/platform=iOS Simulator"
DERIVED_DATA_PATH="./Logs.nosync/DerivedData"
CONFIGURATION="Debug"

xcodebuild build \
  -project PaperClip.xcodeproj \
  -scheme PaperClip \
  -configuration "$CONFIGURATION" \
  -destination "$DESTINATION" \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  -allowProvisioningUpdates \
  COMPILER_INDEX_STORE_ENABLE=NO \
  CODE_SIGNING_ALLOWED=NO \
  | xcbeautify --disable-colored-output | tee -a ./Logs/build_logs.txt
